drop table log if exists;
create table log(
	id bigint generated by default as identity,
	description varchar(100),
	method varchar(100),
	type varchar(100),
	request_ip varchar(100),
	exception_code varchar(100),
	exception_detail varchar(100),
	params varchar(100),
	create_by varchar(100),
  create_date TIMESTAMP,
	primary key(id)
);
